name: ai_learning_app
description: AI Learning App

publish_to: 'none' # If you don't want to publish to pub.dev

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0  # This should be enough for TensorFlow Lite functionality
  http: ^1.2.2
  sqflite: ^2.0.0+4
  path_provider: ^2.0.0
  provider: ^6.0.0
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.1.0
  intl: ^0.20.1
  dio: ^5.0.0
  json_annotation: ^4.8.0
  cupertino_icons: ^1.0.5
  logger: ^2.5.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.2
  connectivity_plus: ^6.1.1
  flutter_lints: ^5.0.0 # Replace with the latest version if necessary


flutter:
  assets:
    - assets/model.tflite

dev_dependencies:
  flutter_test:
    sdk: flutter








